#!/bin/bash
# This will
# - back up /etc/zypp/repos.d
# - back up /etc/zypp/services.d
#
# DISCARDING the old backup, if it exists

set -e
set -u

if test `id -u` -ne 0; then
	echo "Need to be root"
	exit 1
fi

# overwrite SRC DEST
overwrite () {
  rm -rf $2
  cp -a  $1 $2
}

backup () {
  overwrite $1 $1.bak
}

restore () {
  overwrite $1.bak $1
}

if [ "${1-}" = "-r" ]; then
  METHOD=restore
else
  METHOD=backup
fi

$METHOD /etc/zypp/repos.d
$METHOD /etc/zypp/services.d
