#!/bin/bash
set -e
set -u
SERVICE=${1-opensuse-15.4}

if test `id -u` -ne 0; then
    echo "Need to be root"
    exit 1
fi

case "$TERM" in
    screen*) ;;
    *)
        echo 'Warning: using `screen` or `tmux` is recommended just in case your X session dies'
        ;;
esac

zypper removeservice opensuse-15.0 || :
zypper removeservice opensuse-15.1 || :
zypper removeservice opensuse-15.2 || :
zypper removeservice opensuse-15.3 || :
zypper removeservice opensuse || :
SVCDIR=$(cd $(dirname $0); pwd)
zypper addservice file://"$SVCDIR"/$SERVICE opensuse

case "$SERVICE" in
  factory-snapshot)
    RELEASE="openSUSE_Factory" ;;
  opensuse-15.3)
    RELEASE="openSUSE_Leap_15.3" ;;
  opensuse-15.4)
    RELEASE="openSUSE_Leap_15.4" ;;
  *)
    RELEASE="openSUSE_${SERVICE#opensuse-}" ;;
esac
sed -i  "s/openSUSE_\(Leap_\)\?\([0-9][0-9]\\.[0-9]\|Factory\)/$RELEASE/g" /etc/zypp/repos.d/*

zypper --releasever "${RELEASE##*_}" refresh-services
zypper --releasever "${RELEASE##*_}" refresh
zypper --releasever "${RELEASE##*_}" install zypper
zypper --releasever "${RELEASE##*_}" dup
