#!/bin/bash
# TODO:
# - use screen

set -e
set -u
RELEASE=${1-13.1}

if test `id -u` -ne 0; then
    echo "Need to be root"
    exit 1
fi

zypper removeservice opensuse-12.2 || :
zypper removeservice opensuse-12.3 || :
zypper removeservice opensuse || :
SVCDIR=$(cd $(dirname $0); pwd)
zypper addservice file://"$SVCDIR"/opensuse-$RELEASE opensuse
sed -i  "s/1[0-9]\\.[0-9]/$RELEASE/g" /etc/zypp/repos.d/*

zypper refresh-services
zypper install zypper
zypper dup
